---
- name: Running From My GitHub Repository To Devnet-Sandbox
  hosts: all
  gather_facts: false

  tasks:
    - name: configure Loopback 100 & 101 interfaces settings
      ios_config:
        lines:
          - ip address 172.16.1.100 255.255.0.0
          - ip address 172.16.1.101 255.255.0.0
        parents: "{{ item }}"
      with_items:
        - interface Loopback 100
        - interface Loopback 101

    - name: Show IOS Version & Show Route
      ios_command:
        commands:
         - show version | sec IOS
         - show ip interface brief

      register: output
    - debug: var=output.stdout_lines

