---
- name: Running From My GitHub Repository To Devnet-Sandbox
  hosts: all
  gather_facts: false

  tasks:
    - name: Show IOS Version & Show Route
      ios_command:
        commands:
         - show version | sec IOS
         - show ip arp
  
      register: output
    - debug: var=output.stdout_lines
